server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database: h2
    show-sql: true
    generate-ddl: true
    hibernate:
        ddl_auto: update
        
    properties:
      hibernate:
       
        dialect: org.hibernate.dialect.H2Dialect 
  h2:
    console:
      enabled: true
      path: /h2
#  sql:
#    init:
#      data-locations: classpath:data.sql
logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor: TRACE