
INSERT INTO CAR (ID_CAR, TYPE_CAR ) VALUES ('0001CVB', 'SUV');

INSERT INTO CAR (ID_CAR, TYPE_CAR) VALUES ('0002CVB', 'SUV');
INSERT INTO CAR (ID_CAR, TYPE_CAR) VALUES ('0003CVB', 'SUV');
INSERT INTO CAR (ID_CAR, TYPE_CAR) VALUES ('1000CVB', 'PREMIUM');
INSERT INTO CAR (ID_CAR, TYPE_CAR) VALUES ('2000CVB', 'PREMIUM');
INSERT INTO CAR (ID_CAR, TYPE_CAR) VALUES ('3000CVB', 'PREMIUM');
INSERT INTO CAR (ID_CAR, TYPE_CAR) VALUES ('4000CVB', 'PREMIUM');
INSERT INTO CAR (ID_CAR, TYPE_CAR) VALUES ('0100CVB', 'SMALL');
INSERT INTO CAR (ID_CAR, TYPE_CAR) VALUES ('0200CVB', 'SMALL');
INSERT INTO CAR (ID_CAR, TYPE_CAR) VALUES ('0300CVB', 'SMALL');

    